apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: STEMSS-data-prep
  namespace: runai-sample-project
spec:
  environment:
    items:
      WORKSPACE_NAME:
        value: <YOUR_HYPHENATED_NAME>
  name: 
    value: STEMSS-data-prep
  image:
    value: registry.aisingapore.net/aiap-14-dsp/stems-mini-project/data-prep:0.1.0
  imagePullPolicy:
    value: Always
  command:
    value: >-
      /bin/bash -c "source activate stems-mini-project && python src/process_data.py 
      process_data.raw_data_dir_path=/sample-project-pvc/workspaces/$WORKSPACE_NAME/data/mnist-pngs-data-aisg
      process_data.processed_data_dir_path=/sample-project-pvc/workspaces/$WORKSPACE_NAME/data/processed/mnist-pngs-data-aisg-processed"
  workingDir:
    value: /sample-project-pvc/workspaces/$WORKSPACE_NAME/stems-mini-project
  cpu:
    value: '2'
  cpuLimit:
    value: '2'
  memory:
    value: 4G
  memoryLimit:
    value: 4G
  pvcs:
    items:
      pvc-sample-project-pvc:
        value:
          claimName: sample-project-pvc
          existingPvc: false
          path: /sample-project-pvc
          readOnly: false
          readWriteMany: true
          size: 1000G
          storageClass: nfs-client
  username:
    value: STEMSS
